version: '2.4'

services:
    postgres:
        labels:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"

    adminer:
        labels:
            - "traefik.domain=${BASE_URL}"
            - "traefik.frontend.rule=Host:${BASE_URL};PathPrefixStrip:/adminer"

    api:
        environment:
            APICORE_SERVER_URL: "https://${BASE_URL}/api/"
            APICORE_SERVER_INTERFACE: "https://${BASE_URL}/"
            APICORE_DATABASE_PASSWORD: "${DB_PASSWORD}"
        labels:
            - "traefik.frontend.rule=Host:${BASE_URL};PathPrefix:/api/"

    admin:
        environment:
            API_URL: "https://${BASE_URL}/api"
        labels:
            - "traefik.frontend.rule=Host:${BASE_URL}"

    traefik:
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        labels:
            - traefik.enable=true
            - traefik.frontend.rule=Host:traefik.gdqngtrjwxef4flh7u9rutmw.t.michalhosna.com
            - traefik.port=8080
