version: '2.4'

services:
    postgres:
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"

    adminer:
        labels:
            - "traefik.enable=${ENABLE_ADMINER}"
            - "traefik.frontend.rule=Host:${BASE_URL};PathPrefixStrip:/adminer"

    api:
        environment:
            APICORE_SERVER_URL: "https://${BASE_URL}/api/"
            APICORE_SERVER_INTERFACE: "https://${BASE_URL}/"
            APICORE_DATABASE_PASSWORD: "${DB_PASSWORD}"
        labels:
            - "traefik.frontend.rule=Host:${BASE_URL};PathPrefix:/api"

    admin:
        environment:
            API_URL: "https://${BASE_URL}/api"

            APICORE_STORAGE_S3_ENABLED: "${APICORE_STORAGE_S3_ENABLED}"
            APICORE_STORAGE_S3_BUCKET: "${APICORE_STORAGE_S3_BUCKET}"
            APICORE_STORAGE_S3_ACCESS_KEY: "${APICORE_STORAGE_S3_ACCESS_KEY}"
            APICORE_STORAGE_S3_REGION: "${APICORE_STORAGE_S3_REGION}"
            APICORE_STORAGE_S3_SECRET_KEY: "${APICORE_STORAGE_S3_SECRET_KEY}"

            APICORE_JWT_SECRET: "${APICORE_JWT_SECRET}"

            APICORE_SERVER_NAME: "${APICORE_SERVER_NAME}"
            APICORE_SERVER_MAX_UPLOAD_FILESIZE: "${APICORE_SERVER_MAX_UPLOAD_FILESIZE}"

            APICORE_MAIL_EMAIL: "${APICORE_MAIL_EMAIL}"
            APICORE_MAIL_MAILGUN_DOMAIN: "${APICORE_MAIL_MAILGUN_DOMAIN}"
            APICORE_MAIL_MAILGUN_KEY: "${APICORE_MAIL_MAILGUN_KEY}"

            APICORE_AUTH_GITHUB_ENABLED: "${APICORE_AUTH_GITHUB_ENABLED}"
            APICORE_AUTH_GITHUB_CLIENT: "${APICORE_AUTH_GITHUB_CLIENT}"
            APICORE_AUTH_GITHUB_SECRET: "${APICORE_AUTH_GITHUB_SECRET}"
            APICORE_AUTH_GITHUB_HOST: "${APICORE_AUTH_GITHUB_HOST}"
            APICORE_AUTH_GITHUB_API: "${APICORE_AUTH_GITHUB_API}"
            APICORE_AUTH_GITHUB_TEAMS: "${APICORE_AUTH_GITHUB_TEAMS}"

            APICORE_AUTH_GITLAB_ENABLED: "${APICORE_AUTH_GITLAB_ENABLED}"
            APICORE_AUTH_GITLAB_APPLICATION: "${APICORE_AUTH_GITLAB_APPLICATION}"
            APICORE_AUTH_GITLAB_SECRET: "${APICORE_AUTH_GITLAB_SECRET}"
            APICORE_AUTH_GITLAB_HOST: "${APICORE_AUTH_GITLAB_HOST}"
            APICORE_AUTH_GITLAB_API: "${APICORE_AUTH_GITLAB_API}"
            APICORE_AUTH_GITLAB_GROUPS: "${APICORE_AUTH_GITLAB_GROUPS}"

        labels:
            - "traefik.frontend.rule=Host:${BASE_URL}"

    traefik:
        ports:
            - 80:80
            - 443:443
        labels:
            - traefik.enable=true
            - traefik.frontend.rule=Host:traefik.gdqngtrjwxef4flh7u9rutmw.t.michalhosna.com
            - traefik.port=8080
