version: '2.4'

services:
    postgres:
        labels:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"

    adminer:
        labels:
            - "traefik.domain=${BASE_URL}"
            - "traefik.enable=${ENABLE_ADMINER}"

    api:
        environment:
            APICORE_SERVER_URL: "https://${BASE_URL}/api/"
            APICORE_SERVER_INTERFACE: "https://${BASE_URL}/"
        labels:
            - "traefik.domain=${BASE_URL}"

    admin:
        environment:
            API_URL: "https://${BASE_URL}/api"
            APICORE_DATABASE_PASSWORD: "${DB_PASSWORD}"
        labels:
            - "traefik.domain=${BASE_URL}"

    traefik:
        ports:
            - 80:80
            - 443:443

