defaultEntryPoints = ["http", "https"]
logLevel = "INFO"

[api]
address = ":8080"
  [api.statistics]
  recentErrors = 20

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]


[acme]
email = "${ACME_EMAIL}" #TODO
storage = "/acme-storage/acme.json"
onHostRule = true
acmeLogging = true
caServer = "${ACME_SERVER}" #TODO
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker"
exposedbydefault = false

[accessLog]
[ping]
entryPoint = "http"
